using NUnit.Framework;
using Shouldly;

namespace AdventOfCode.Tests._2025;

public class Day7
{
    private Days._2025.Day7 _day7;

    [SetUp]
    public void Initialize()
    {
        _day7 = new Days._2025.Day7();
    }

    [Test]
    [TestCase(
        """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """,
        21
    )]
    public void Part1_should_count_how_many_times_particle_splitted(
        string testInput,
        int expectedResult
    )
    {
        var parsedInput = _day7.ParseRawInput(testInput);

        var result = _day7.Part1(parsedInput);

        result.ShouldBe(expectedResult);
    }

    [Test]
    [TestCase(
        """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """,
        40
    )]
    public void Part2_should_count_how_many_timelines_particle_could_go(
        string testInput,
        int expectedResult
    )
    {
        var parsedInput = _day7.ParseRawInput(testInput);

        var result = _day7.Part2(parsedInput);

        result.ShouldBe(expectedResult);
    }
}
