using System.Collections.Generic;
using AdventOfCode.Days._2024;
using AdventOfCode.Days.Common;
using NUnit.Framework;
using Shouldly;

namespace AdventOfCode.Tests._2024;

public class Day6
{
    private Days._2024.Day6 _day6;

    [SetUp]
    public void Initialize()
    {
        _day6 = new Days._2024.Day6();
    }

    [Test]
    public void ParseRawInput_returns_map_as_2d_char_array()
    {
        const string rawInput = """
                                ....#.....
                                .........#
                                ..........
                                ..#.......
                                .......#..
                                ..........
                                .#..^.....
                                ........#.
                                #.........
                                ......#...
                                """;

        var parsedInput = _day6.ParseRawInput(rawInput);

        parsedInput.GuardPos.ShouldBe(new Point(6, 4));
        parsedInput.Obstacles.ShouldBe(
        [
            new Point(0, 4),
            new Point(1, 9),
            new Point(3, 2),
            new Point(4, 7),
            new Point(6, 1),
            new Point(7, 8),
            new Point(8, 0),
            new Point(9, 6)
        ]);
        parsedInput.Rows.ShouldBe(10);
        parsedInput.Rows.ShouldBe(10);
    }

    [Test]
    [TestCase("""
              ....#.....
              .........#
              ..........
              ..#.......
              .......#..
              ..........
              .#..^.....
              ........#.
              #.........
              ......#...
              """, 41)]
    public void Part1_returns_number_of_visited_positions_by_guard(string testInput, int expectedResult)
    {
        var result = _day6.Part1(_day6.ParseRawInput(testInput));

        result.ShouldBe(expectedResult);
    }

    [Test]
    [TestCase("""
              ....#.....
              .........#
              ..........
              ..#.......
              .......#..
              ..........
              .#..^.....
              ........#.
              #.........
              ......#...
              """, 6)]
    [TestCase("""
              ....#.....
              ...#.#....
              ..........
              ..........
              ..........
              ..........
              ....^....#
              ..........
              ...#......
              ........#.
              """, 1)]
    [TestCase("""
              ....#...
              ...#....
              ^.......
              """, 0)]
    [TestCase("""
              ^........
              .........#
              .........#
              """, 0)]
    [TestCase("""
              #.........
              .........#
              ..........
              ..........
              ..........
              ..........
              ^.........
              ..........
              .#........
              ........#.
              """, 99)]
    public void Part2_returns_number_of_placed_obstructions_that_makes_guard_go_into_loop(string testInput, int expectedResult)
    {
        var result = _day6.Part2(_day6.ParseRawInput(testInput));

        result.ShouldBe(expectedResult);
    }
}
